baseURL = 'https://www.foriero.it/'
languageCode = 'en-us'
title = 'Foriero'
theme = "hugo-hero-theme"
enableRobotsTXT = true

[module]
  [module.hugoVersion]
    extended = true
    min = "0.92.0"
    
[params]
  google_analytics_id="G-HTBTCGZP72"

  [params.logo]
    mobile = "images/logo-mobile.svg"
    mobile_height = "36px"
    mobile_width = "36px"
    desktop = "images/logo.svg"
    desktop_height = "48px"
    desktop_width = "300px"
    alt = "Foriero"

  [params.homepage_meta_tags]
    meta_description = "Foriero is a creative digital agency that puts your business first. Learn more here."
    meta_og_title = "Foriero Srl"
    meta_og_type = "website"
    meta_og_url = "https://foriero.it/"
    meta_og_image = "https://foriero.it/images/meta_og_image.png"
    meta_og_description = "Foriero is a creative digital agency that puts your business first. Learn more here."
    ## Not used
	# meta_twitter_card = "summary"
    # meta_twitter_site = "@zerostaticio"
    # meta_twitter_creator = "@zerostaticio"

[sitemap]
  changefreq = 'monthly'
  filename = 'sitemap.xml'
  priority = 0.5

[[menu.main]]
	name = "Services"
	url = "/services/"
    weight = 1

#[[menu.main]]
#    name = "Work"
#    url = "/work/"
#    weight = 2

[[menu.main]]
    name = "About"
    url = "/about/"
    weight = 3

#[[menu.main]]
#    name = "History"
#    url = "/history/"
#    weight = 3

[[menu.main]]
    name = "Contact"
    url = "/contact/"
    weight = 4

[permalinks]
  post = "/:year/:month/:day/:slug/"
  pages = "/:filename/"
